### ISSUE TITLE
PourOver View is broken

### ISSUE THREAD

**Issue by zzeniou86** [NYTimes/pourover#40]
Hello, I have tried the example codes for Views and it doesn't work. 

A View won't update its matchset when overriding the selectionFn(). You need to do naturalSelectionFn() manually or change the .matchset object.

Moreover, the example with change event to render a console.log also does not work as it is.

Lastly, removing items from a collection is also broken.

**Comment by hhsnopek** [comment]
@zzeniou86 I recently moved the tests for pourover and they all are passing. Would you be able to give examples of the code you were trying?
