### ISSUE TITLE
DB on top of PourOver

### ISSUE THREAD

**Issue by mehdi-cit** [NYTimes/pourover#43]
Hello everyone.
I posted a similar question in CrossFilter github issue's list and someone directed me here! So here's a copy of the question. I hope someone can clarify if it's possible to use PourOver for what I want to do.
I'm investigating how to create an in memory "relational/object" database in the browser. I wonder whether it's feasible and/or desirable to use PourOver as an indexing/querying engine for it.
Let's consider this scenario:
I have some json stored in localStorage (maximum 5 MB). I want to load it into memory and start querying (create get update delete...). The data model/schema is two entities (Student and Class) related by (takes/takenBy) a Many-to-Many relationship. [Student] --takes--> [Class].
Student:[ {id:0, name:adam, age:22},{id:1, name:Eva, age:29},{id:2, name:Abel, age:7}]
Class:[ {id:0, name:Math, Day:1},{id:1, name:Poetry, Day:1},{id:2, name:Math, Day:Tue}]
Takes:[
{StudentID:0 , ClassID:0 },
{StudentID:0 , ClassID:1 },
{StudentID:1 , ClassID:1 },
{StudentID:1 , ClassID:2 },
{StudentID:2 , ClassID:2 },
]
Let's say that I load each of the above (two entities + the relation) to its own 'PourOver collection'. 
I also create a 'high-level' query engine on top of PourOver. This engine would use the three 'PourOver collections' to query the data and do some joins etc. 
I want it to be able not only to query/get but also to create/add, update and delete.
When the user is done, the in memory data is stored back in the localStorage.

I would like to have PourOver users/creators' opinions before trying such thing. If there's something inherent to PourOver that would hinder such approach I'd prefer to know that in advance.

I had a quick look and it seems PourOver's singleton is not meant to handle more than a collection. I'm saying that because of the line (basic example): 
PourOver.makeExactFilter("mythology", ["greek","norse"]); 
To me it looks like it's using the PourOver "singleton" to create a filter for one collection. This would mean no two collection can have the same filter-name (i.e. field name).
etc...
Thank you much for your time.

**Comment by bkoski** [comment]
This seems related to #60 -- currently we only support filtering against top-level attributes to keep the query logic simple and efficient.
