### ISSUE TITLE
Cant delete the items in the collection

### ISSUE THREAD

**Issue by khyamay** [NYTimes/pourover#45]
I was going through the example as shown on the home page and it says that you can remove the item in the collection by using collection.removeItems(1) but its doesn't work but whenever I pass the cid explicitly like collection.removeItems({cid: 1}), it works fine. Am i missing something here? or it is a typo or is there any reason for it??? Thanks

**Comment by tiffehr** [comment]
Fixed the documentation.  It was wrong, for the fact that it had a hard-coded `_.pluck(i,"cid")` in the singular case and just flat-out expected in in the sorted/`true` optional flag case.

I realize this is significantly out of date for your question but thank you so much for pointing out the issue!
