### ISSUE TITLE
request for PourOver website to load the pourover.js file

### ISSUE THREAD

**Issue by mg1075** [NYTimes/pourover#53]
Just a request for the PourOver website...

http://nytimes.github.io/pourover/

It would be nice if the website could include the pourover.js file thereby making it possible to play along with the examples in the console. Lodash, for instance, has this on the lodash website, and it really comes in handy when you need to try a quick experiment while reading about the api.

**Comment by tiffehr** [comment]
+1
This was one of my own requests in helping copyedit the original documentation.  I'll be poking around in the documentation soon and will see what I can do.

**Comment by tiffehr** [comment]
My current plan is to fold this into #41, hoping to provide less conceptual documentation but with something like a JSFiddle area to play with a sample PourOver dataset.

**Comment by tiffehr** [comment]
Okay, PourOver is available as a global object `PourOver` if you open dev-tools on [the PourOver book main page](http://nytimes.github.io/pourover/).  

However, that's only party helpful.  I'll need to dig through Jekyll to get the .js files associated correctly with its build to wrapper the subsequent pages.  Tonight's not the night for that work, however.
