### ISSUE TITLE
Aggregation with pourover

### ISSUE THREAD

**Issue by msalamon1** [NYTimes/pourover#61]
Really more of a question. I have been evaluating crossfilter and this seems to do several similar things and in many ways it easier.

Does pourover have any capabilities to perform aggregation on the entire data set or any slices of that data?  is this on the roadmap?

Thanks!

**Comment by tiffehr** [comment]
Currently there is nothing on the roadmap except bugfixes and sensible pull-requests.  

I'm not sure I follow your question, though, regarding aggregation.  Can you explain perhaps with a small JS sample what you'd hope it does?

**Comment by msalamon1** [comment]
I'm not sure I can provide a JS sample.  My only hope was that after I performed a filter on the data, I could also group the data an aggregate it. For example, if my data set is baseball players, I could filter on catchers in the national league and then get the total home runs for those catchers, or the on base percentage average for those catchers, etc.     Or I could group all catchers by National League and American League and get the no base percentage average for all catchers by League.

other libraries, like crossfilter, can do those types of things.

**Comment by tiffehr** [comment]
You can combine existing filters, doing the additions or negations you seem to want in that example.  It wouldn't automatically know or give you answers from those combinations—total home runs, in our example.  But it can definitely intersect catchers and leagues.  From the combination, you could then calculate something like total home runs.

@esmooov built a lot of PourOver while working on this Interactive, for the NYT:  http://www.nytimes.com/interactive/2014/02/02/fashion/red-carpet-project.html?_r=0

Under the hood, it makes extensive use of filters and then provides user-facing tools to do the intersections of them all.  So you can combine years, designers and colors all at once, then show the results.  Or calculate something from the results, to go back to your baseball example.

In the (admittedly sparse) documentation, [Advanced Views](http://nytimes.github.io/pourover/examples/examples_build/advanced_views.html#section-2) seems to explain how you might intersect filters you've created.

**Comment by msalamon1** [comment]
Thanks. So I would need to grab the data and do any calculations myself, including determining the count of the number of items returned by the filters.

**Comment by tiffehr** [comment]
No, it'll tell you how many things match the intersection of your filters—the length of the current query's cids is that measure.  So if you have 5 catchers and 2 are NL and 3 are AL, intersecting `catchers.and(nl)` will return 2 cids, keyed to the two matching players in your data.  But it's your responsibility to know what tally means.  PourOver's not going to know anything other than what data matches the current intersected logic.

**Comment by tiffehr** [comment]
Feel free to reopen if you'd like more help.
