### ISSUE TITLE
[question] Any thoughts of node?

### ISSUE THREAD

**Issue by Shadowstep33** [NYTimes/pourover#66]
I am currently working on a project that would benefit greatly from the magical goodness of pourover filtering. I could definitely get a lot of power out of using it in browser, but in my specific context it would make more sense using it on node. 

Thusly, I'm here and curious. Any intentions of adding to npm?

**Comment by hhsnopek** [comment]
Hey @Shadowstep33 - check out the [community fork](//github.com/hhsnopek/pourover)/[npmjs link](//www.npmjs.com/package/pourover)

**Comment by Shadowstep33** [comment]
Cool, thanks! I'll have to check this out
